name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Configurar Credenciales de GameMaker
      run: |
        # Creamos la ruta física para inyectar tus secrets en el compilador
        mkdir -p ~/.config/GameMakerStudio2
        echo '{
          "login": "${{ secrets.GM_USERNAME }}",
          "password": "${{ secrets.GM_PASSWORD }}",
          "will_login": true
        }' > ~/.config/GameMakerStudio2/local_settings.json

    - name: Set up GameMaker Igor Compiler
      uses: bscotch/igor-setup@v1
      with:
        # Apuntamos a tu archivo para que lea la versión interna
        target-yyp: 'SMM_WE.yyp' 
        # Forzamos los parámetros del archivo local_settings creado arriba
        local-settings-override-file: '~/.config/GameMakerStudio2/local_settings.json'

    - name: Compile iOS Project
      uses: bscotch/igor-build@v1
      with:
        project-path: 'SMM_WE.yyp'
        target: 'ios'
        command: 'package'
        # Pasamos el inicio de sesión nativo requerido en la compilación
        username: ${{ secrets.GM_USERNAME }}
        password: ${{ secrets.GM_PASSWORD }}
        xcode-arguments: 'CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""'

    - name: Upload Finished IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-ipa
        path: |
          **/*.ipa
          **/*.xcarchive
